//
// Created by moe on 2017-07-04.
//

#include "PropertyValueVisitor.hpp"

#define DEFINE_VISITOR_METHOD(type)\
void PropertyValueVisitor::Visit(PropertyValue<type>* pv){}\
void PropertyValueVisitor::Visit(PropertyValueArray<type>* pv){}

namespace Kedama
{
	DEFINE_VISITOR_METHOD(int32_t)
	DEFINE_VISITOR_METHOD(uint32_t)
	DEFINE_VISITOR_METHOD(float)
	DEFINE_VISITOR_METHOD(double)
	DEFINE_VISITOR_METHOD(bool)
	DEFINE_VISITOR_METHOD(vec2)
	DEFINE_VISITOR_METHOD(vec3)
	DEFINE_VISITOR_METHOD(vec4)
	DEFINE_VISITOR_METHOD(ivec2)
	DEFINE_VISITOR_METHOD(ivec3)
	DEFINE_VISITOR_METHOD(ivec4)
	DEFINE_VISITOR_METHOD(bvec2)
	DEFINE_VISITOR_METHOD(bvec3)
	DEFINE_VISITOR_METHOD(bvec4)
	DEFINE_VISITOR_METHOD(uvec2)
	DEFINE_VISITOR_METHOD(uvec3)
	DEFINE_VISITOR_METHOD(uvec4)
	DEFINE_VISITOR_METHOD(dvec2)
	DEFINE_VISITOR_METHOD(dvec3)
	DEFINE_VISITOR_METHOD(dvec4)
	DEFINE_VISITOR_METHOD(mat2)
	DEFINE_VISITOR_METHOD(mat3)
	DEFINE_VISITOR_METHOD(mat3x4)
	DEFINE_VISITOR_METHOD(mat4)

	DEFINE_VISITOR_METHOD(ITexture2DArray*)
	DEFINE_VISITOR_METHOD(ITexture2D*)
	DEFINE_VISITOR_METHOD(ITextureCube*)
	DEFINE_VISITOR_METHOD(ITextureCubeArray*)
	DEFINE_VISITOR_METHOD(ITexture3D*)
}